### ISSUE TITLE
Logging from pipelines

### ISSUE THREAD

**Issue by tpluscode** [zazuko/barnard59-core#10]
We were discussing an API for logging from pipelines. Its primary use would be to track execution progress, especially when running on a web node.

I expect that such API should be no different from simple `console.log` but enriched with contextual information about the current pipeline/step.

**Comment by bergos** [comment]
Events which could be interesting for logging:
- step init started
- step init finished
- step processing started
- step processing finished

**Comment by tpluscode** [comment]
Closed by #26
