### ISSUE TITLE
Make Pipeline itself a Readable, Writable, Duplex stream

### ISSUE THREAD

**Issue by bergos** [zazuko/barnard59-core#27]
The pipeline factory should return a Stream which implements Readable, Writeable according to the pipeline description. Three different class are required to provide all possibilities. `PipelineReadable`, `PipelineWritable`, `PipelineDuplex` should inherit from a `Pipeline` or `PipelineCore` class which contains most of the logic of the current `Pipeline` class.

**Comment by tpluscode** [comment]
I think this one can be closed now that #31 is merged?
