### ISSUE TITLE
Data types lost from pipeline variables

### ISSUE THREAD

**Issue by tpluscode** [zazuko/barnard59-core#5]
## Description 

While trying out what I describe in zazuko/barnard59#116 I stumbled across an apparent bug but I wasn't able to pinpoint its source. Just as described in zazuko/barnard59#116, I added a variable to the csvw example pipeline

```diff
<parseCsvw> a p:Pipeline;
  p:variables [
    p:variable [
      p:name "filename";
      p:value "examples/test.csv";
    ], [
      p:name "metadata";
      p:value "examples/test.csv-metadata.json";
+    ], [
+      p:name "jsPad";
+      p:value 2
     ]
   ];
```

I then inspected what's happening  in `pipeline.js` and discovered that by the time the execution gets to [`parseVariables`](https://github.com/zazuko/barnard59-core/blob/885c0e67112aff1ed955cfa1c1d229961abd92ce/lib/pipeline.js#L122) all variables' terms have no datatype.

```js
// all undefined
variableNodes.map(t => typeof t.out(ns.p('value')).term.dataType)
```

Don't know what's going on. I assumed it may be a problem with clownface, but parsing the same graph and passing to CF dataset does indeed preserve all datatypes. And of course all `^^code:ecmaScriptTemplateLiteral` is just fine...

**Comment by bergos** [comment]
Think it's just a typo: `dataType` -> `datatype`

**Comment by tpluscode** [comment]
Yes, sorry ☺️
