### ISSUE TITLE
[Feature] Required variables

### ISSUE THREAD

**Issue by tpluscode** [zazuko/barnard59-core#53]
I propose to have value-less variables declared on a pipeline which would allow a fail-fast if a given variable is provided by the caller or parent pipeline

```turtle
<#LoadCsv>
  :steps [ :stepList ( _:openCsvFromS3Bucket ) ] ;
  :variables [ :variable
    [ a :Variable; :name "S3-ENDPOINT"; :required true ]
  ].
```

This should throw when the variables is loaded and it still has no value

**Comment by l00mi** [comment]
close for https://github.com/zazuko/barnard59-core/issues/16
