### ISSUE TITLE
Throw error if undefined variable is used

### ISSUE THREAD

**Issue by bergos** [zazuko/barnard59-core#62]
If an undefined variable is used, the variable loader should throw an error.

**Comment by tpluscode** [comment]
This looks like it may require a major version. Will most definitely break some pipelines @ludovicm67

**Comment by ludovicm67** [comment]
Yes, a major version should be needed to avoid breaking pipelines.

An additional suggestion is to add a `allowEmpty` parameter for some specific variables in case it's needed.

**Comment by tpluscode** [comment]
...or the opposite, to have a `:required` property

In that case a major version may not be necessary

**Comment by ludovicm67** [comment]
We can start that way, and then the day we want to do a major version do the change to have it required by default? As this will help to prevent typos and so on on variables names.

**Comment by tpluscode** [comment]
The argument about typos is quite compelling. The main package which depends on `-core` is `barnard59`. I'm thinking that even if we introduce a breaking change here, we might have the version range as `1 - 2` and let final projects update core to v2 when they are ready
