### ISSUE TITLE
Referencing variables in step arguments as RDF nodes

### ISSUE THREAD

**Issue by tpluscode** [zazuko/barnard59-core#9]
Current way for using variables is a bit verbose when a variables is to be passed as-is into a step. Here's an excerpt from the example, slightly modified by extracting the variable `url` into a named node

```
<utc> a p:Pipeline ;
  p:variables [
    p:variable var:url
  ]  .

var:url p:Variable ;
  p:name "url" ;
  p:value "http://worldclockapi.com/api/json/utc/now" .

<fetch> a p:Step ;
  p:arguments ( "${url}"^^code:ecmaScriptTemplateLiteral ) .
```

With a variable having its own node it should be simpler to pass it around as reference instead of doing the ES6 Template String literal.

```
<fetch> a p:Step ;
  p:arguments ( var:url ) .
```

**Comment by bergos** [comment]
I like it. That's actual the same approach like for the [forEach sup-pipeline argument](https://github.com/zazuko/barnard59-core/blob/master/examples/forEach.js#L62). We should handle that generic in the code. Can you just temporary change the variable definition in you example like this:

```
var:url a p:Variable ;
  p:name "url" ;
  p:value "http://worldclockapi.com/api/json/utc/now" .
```

Later we implement a very simple/stupid reasoner which adds the rdf:type.

But with the rdf:type we can use the generic approach of the code loader also for the vars. If we have other cases in the future, we just need to register a new handler for the rdf:type.

**Comment by tpluscode** [comment]
I added the variable type but is it really necessary? Would we not just assumes that if it looks like a duck and quacks like duck then it's a variable?

**Comment by bergos** [comment]
But then it's hard coded in the code. We have already the code use case, the pipeline use case and now the variable use case. Can we unify them somehow with the [CodeLoader](https://github.com/zazuko/barnard59-core/issues/1)? Mabe we rename it to `JavaScriptLoader` or something like that, so it's no longer just for code, but any kind of Linked Data description translated into JS types.
